### PR TITLE
Add PointingProvider

### PR DESCRIPTION
**Pull request by mreineck**

### CODE REVIEW

**Comment by ziotom78** [comment]
Hi @mreineck , sorry for the delay in my comments. This implementation looks very handy!

One minor point: I see that `PyPointingProvider::pyget_rotated_quaternions` allocates the array where to store the result. Would it make sense to provide a similar method where the result array is passed as argument? In this way one could allocate the array once and then iterate the call to `pyget_rotated_quaternions` while re-using the same array, reducing the time needed for memory allocation.

**Comment by mreineck** [comment]
Sure, that can be done easily!

**Comment by mreineck** [comment]
An implementation-detail question for @tskisner: what is the internal storage format for quaternions in TOAST? w,x,y,z or x,y,z,w? I'm trying to avoid confusion wherever possible, so I'd like to use the same order.

**Comment by mreineck** [comment]
I should perhaps note that functionality which is very similar to the `PointingProvider` can be emulated using `scipy.spatial.transform` (I just noticed this while writing unit tests). It appears to be roughly a factor of 10 slower, but this is not necessarily a big deal. So if there is preference for using `scipy` here, that's absolutely fine with me.

In any case I'll use the (x,y,z,w) ordering for quaternions in my code to be compatible with `scipy` in that respect.

**Comment by tskisner** [comment]
Hello @mreineck , sorry for the delayed response.  TOAST currently uses "scalar last" format, but there have been requests to support "scalar first" as well (used by Boost quaternions).  Our issue for tracking that (which I just updated) is here:  https://github.com/hpc4cmb/toast/issues/335

**Comment by mreineck** [comment]
Thanks! Scalar-last it is then, at least for the time being.

**Pull request merged**
